# Generated by Django 5.2.14 on 2026-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video langsung ke server.', null=True, upload_to='lessons/videos/', verbose_name='File Video (Upload)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link video materi (YouTube)', null=True, verbose_name='URL Video (YouTube)'),
        ),
    ]
