# Generated by Django 5.2.14 on 2026-05-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_video_file_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, help_text='File dokumen pendukung (PDF, Docx, dll.)', null=True, upload_to='lessons/attachments/', verbose_name='Lampiran Dokumen'),
        ),
    ]
