# Generated by Django 5.2.14 on 2026-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_assignment_quiz_quizattempt_quizquestion_quizanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Isi 0 jika tidak ada batas waktu.', verbose_name='Waktu Pengerjaan (Menit)'),
        ),
    ]
