# Generated by Django 5.2.14 on 2026-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quiz_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('quiz', 'Kuis'), ('exam', 'Ujian')], default='quiz', max_length=10, verbose_name='Tipe'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Judul'),
        ),
    ]
