# Generated by Django 5.2.14 on 2026-05-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_quiz_quiz_type_alter_quiz_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Pertemuan')),
                ('meeting_link', models.URLField(max_length=500, verbose_name='Link Pertemuan (GMeet/Zoom)')),
                ('start_time', models.DateTimeField(verbose_name='Waktu Mulai')),
                ('end_time', models.DateTimeField(verbose_name='Waktu Selesai')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi/Catatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course', verbose_name='Kursus')),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
