# Generated by Django 5.2.14 on 2026-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_livesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Pengumuman')),
                ('file', models.FileField(blank=True, null=True, upload_to='announcements/files/', verbose_name='File Lampiran')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Tautan (Link) Eksternal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampilkan')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Terbit')),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-published_at'],
            },
        ),
    ]
