# Generated by Django 5.2.14 on 2026-05-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file untuk soal mendengarkan.', null=True, upload_to='quizzes/audio/', verbose_name='File Audio (Listening)'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file untuk soal mendengarkan ini.', null=True, upload_to='questions/audio/', verbose_name='File Audio (Listening)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('quiz', 'Kuis'), ('exam', 'Ujian'), ('listening', 'Mendengarkan')], default='quiz', max_length=10, verbose_name='Tipe'),
        ),
    ]
