# Generated by Django 5.2.14 on 2026-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_quiz_audio_file_quizquestion_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload file gambar untuk soal ini.', null=True, upload_to='questions/images/', verbose_name='Gambar Soal'),
        ),
    ]
