# Generated by Django 5.2.14 on 2026-05-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_quizquestion_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Atau masukkan URL audio langsung (hanya baca, tanpa unduh ke server).', max_length=500, null=True, verbose_name='URL Audio (Listening)'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_url',
            field=models.URLField(blank=True, help_text='Atau masukkan URL gambar langsung (hanya baca, tanpa unduh ke server).', max_length=500, null=True, verbose_name='URL Gambar Soal'),
        ),
    ]
