# Generated by Django 5.2.14 on 2026-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_quizquestion_audio_url_quizquestion_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/submissions/audio/', verbose_name='File Audio Jawaban'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link/URL Jawaban'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/submissions/', verbose_name='File Jawaban'),
        ),
    ]
