# Generated by Django 5.2.14 on 2026-06-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_assignmentsubmission_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment_url',
            field=models.URLField(blank=True, help_text='Tautan eksternal (Google Drive, dll.) untuk dokumen materi.', max_length=500, null=True, verbose_name='Link/URL Dokumen'),
        ),
    ]
