# Generated by Django 5.2.14 on 2026-05-15 19:38

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGradeRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Rekap Nilai',
                'verbose_name_plural': 'Rekap Nilai Siswa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
